---

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  # "Check for added large files"
  - id: check-added-large-files
  # "Check for merge conflicts"
  - id: check-merge-conflict
  # "Check Yaml"
  - id: check-yaml
    args:
      # Allow custom tags like Gitlab's "!reference" tag.
      - --unsafe
    exclude: ^helm/.+/templates/
  # "Trim Trailing Whitespace"
  - id: trailing-whitespace

# "Commit messages"
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.4.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]

- repo: "https://git.knut.univention.de/univention/infrastructure/pre-commit-hooks/check-issue-reference"
  rev: "v1.0.1"
  hooks:
    - id: "check-issue-reference"
      name: "Check issue reference"

# "Dockerfile linter"
- repo: https://gitlab.com/univention/pre-commit-hooks/docker-pre-commit
  rev: v2.0.0
  hooks:
  - id: hadolint-system
    args:
      - --ignore
      - DL3059
      - --ignore
      - DL3008

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.4
  hooks:
    - id: insert-license
      name: insert license in docker files
      description: Insert license in Docker files.
      files: docker\/.*\/.*Dockerfile$
      args:
        - --license-filepath
        - license_header.txt
        - --use-current-year
        - --detect-license-in-X-top-lines=35
    - id: insert-license
      name: insert license in bash files
      description: Insert license in Bash files.
      files: docker\/.*\/.*.sh$
      args:
        - --license-filepath
        - license_header.txt
        - --use-current-year
        - --detect-license-in-X-top-lines=35
...
